### ISSUE TITLE
can't find trax lib

### ISSUE THREAD

**Issue by andyhx** [davheld/GOTURN#1]
hi,I am compiling the code,I rebuild my caffe using  Cmake ,but now  I am having these linking  problems, I download from https://github.com/votchallenge/trax/ get trax to build trax libraries and linking it,but it did not help,Do I have to rebuild trax,linking to project? Has anyone succeeded  building it ? Want help ,Thank you !

errors are like followings:

`[ 80%] Built target show_imagenet
[ 84%] Built target show_tracker_alov
[ 88%] Built target show_tracker_vot
[ 92%] Built target test_tracker_alov
Linking CXX executable test_tracker_vot
libGOTURN.a(vot.cpp.o): In function`VOT::vot_initialize()':
vot.cpp:(.text+0x25c): undefined reference to `trax_server_setup'
vot.cpp:(.text+0x274): undefined reference to`trax_server_wait'
vot.cpp:(.text+0x27e): undefined reference to `trax_image_get_path'
vot.cpp:(.text+0x29a): undefined reference to`trax_server_reply'
vot.cpp:(.text+0x2de): undefined reference to `trax_region_get_rectangle'
vot.cpp:(.text+0x2e8): undefined reference to`trax_region_release'
vot.cpp:(.text+0x2f2): undefined reference to `trax_image_release'
libGOTURN.a(vot.cpp.o): In function`VOT::vot_frame()':
vot.cpp:(.text+0x64d): undefined reference to `trax_server_wait'
vot.cpp:(.text+0x660): undefined reference to`trax_image_get_path'
vot.cpp:(.text+0x675): undefined reference to `trax_image_release'
libGOTURN.a(vot.cpp.o): In function`VOT::vot_report(vot_region_)':
vot.cpp:(.text+0x6e6): undefined reference to `trax_region_create_rectangle'
vot.cpp:(.text+0x6f9): undefined reference to`trax_server_reply'
vot.cpp:(.text+0x703): undefined reference to `trax_region_release'
libGOTURN.a(vot.cpp.o): In function`VOT::vot_quit()':
vot.cpp:(.text+0x4cc): undefined reference to `trax_cleanup'
collect2: error: ld returned 1 exit status
CMakeFiles/test_tracker_vot.dir/build.make:175: recipe for target 'test_tracker_vot' failed
make[2]: *_\* [test_tracker_vot] Error 1
CMakeFiles/Makefile2:305: recipe for target 'CMakeFiles/test_tracker_vot.dir/all' failed
make[1]: **\* [CMakeFiles/test_tracker_vot.dir/all] Error 2
Makefile:75: recipe for target 'all' failed
make: **\* [all] Error 2
`

**Comment by davheld** [comment]
I actually did not integrate my tracker into the trax framework; instead I used the approach described here: http://www.votchallenge.net/howto/integration.html
which is integrated in test_tracker_vot.cpp

**Comment by andyhx** [comment]
thx,I solved it myself
here is my solution:
 download trax https://github.com/votchallenge/trax/  and make  it
adding this  in the cmakelist 
add_executable (test_tracker_vot src/test/test_tracker_vot.cpp)
target_link_libraries(${PROJECT_NAME} ${OpenCV_LIBS} ${Caffe_LIBRARIES})
#target_link_libraries(${PROJECT_NAME} /home/public/git/vot-toolkit/tracker/examples/native/static_cpp.so)
#LINK_LIBRARIES("/home/public/git/trax/build/libtrax.so")
target_link_libraries(${PROJECT_NAME} /home/public/git/trax/build/libtrax.so)
target_link_libraries (test_tracker_vot ${PROJECT_NAME})

**Comment by davheld** [comment]
Nice!

**Comment by ujsyehao** [comment]
@andyhx Can you upload the entire CMakelist, I don't know how to put these in the file?

**Comment by ujsyehao** [comment]
@davheld I don't know what andyhx says. #target_link_libraries(${PROJECT_NAME} /home/public/git/vot-toolkit/tracker/examples/native/static_cpp.so). I cannot find toolkit in my computer. So can you solve it ?

**Comment by VictoriaW1** [comment]
@ujsyehao  I have just encountered this problem and solved it by following the steps of andyhx:

- First, download [trax](https://github.com/votchallenge/trax/). Then from the trax directory, type:
```
mkdir build
cd build 
cmake ..
make
```
- Second, modify CMakeLists.txt of GOTURN around row 84:
```
# Note: If can't find trax, please download trax and build it, then uncomment the below line and set the path manually
target_link_libraries(${PROJECT_NAME} /home/victoria/open_source/GOTURN/src/native/trax/build/libtrax.so)
```
You should set your trax path. ^ ^

**Comment by ujsyehao** [comment]
@VictoriaW1 @andyhx Thank you! we will appreciate you.
