### ISSUE TITLE
What is the meaning of edge effects?

### ISSUE THREAD

**Issue by weiweikong** [davheld/GOTURN#11]
What is the meaning of `edge effects` mentioned in file `image_proc.cpp` ?
- It seems `edge effects` related to whether remains the edge pixels as ROI ?
- In `image_proc.cpp` code
  - The `output_image` initialized as an all black image with `output_height * output_width`
  - Then, the `cropped_image`, which is smaller than `output_image`, insert into the all black image.
  - So cropped result, which return to `*pad_image`, has a black edge with 1 pixel?

Why should we consider the edge effect?

**Comment by davheld** [comment]
The crop from the previous frame (which is input to our network) needs to contain the target object in the center of the crop.  If the target is near the border of the image, then this requires padding the crop with black pixels such that the target object is still in the center of the crop.  This is the meaning of "edge effects."
