### ISSUE TITLE
make erro about caffe

### ISSUE THREAD

**Issue by ghost** [davheld/GOTURN#25]
Hi, thank you for your sharing~
 And when  i try to follow this install instruction to setup this package,i encounter this error:

[ 25%] Building CXX object CMakeFiles/GOTURN.dir/src/network/regressor.cpp.o
In file included from /home/siahooar/caffe/include/caffe/caffe.hpp:7:0,
                 from /home/siahooar/GOTURN/src/network/regressor.h:4,
                 from /home/siahooar/GOTURN/src/network/regressor.cpp:1:
/home/siahooar/caffe/include/caffe/blob.hpp:9:34: fatal error: caffe/proto/caffe.pb.h: No such file or directory
compilation terminated.
CMakeFiles/GOTURN.dir/build.make:254: recipe for target 'CMakeFiles/GOTURN.dir/src/network/regressor.cpp.o' failed
make[2]: *** [CMakeFiles/GOTURN.dir/src/network/regressor.cpp.o] Error 1
CMakeFiles/Makefile2:215: recipe for target 'CMakeFiles/GOTURN.dir/all' failed
make[1]: *** [CMakeFiles/GOTURN.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
 
Can you give me some advise to solve it?

**Comment by fujihuang** [comment]
@davheld

**Comment by puface** [comment]
run command :
protoc src/caffe/proto/caffe.proto --cpp_out=.
 mkdir include/caffe/proto
mv src/caffe/proto/caffe.pb.h include/caffe/proto

**Comment by ghost** [comment]
thx~,it did work~
