### ISSUE TITLE
error happened when make (about lopencv_dep_lcudart)

### ISSUE THREAD

**Issue by ghost** [davheld/GOTURN#27]
Hi,when i try to make this package,i encountered this error:

[ 77%] Linking CXX executable train
/usr/bin/ld: cannot find -lopencv_dep_cudart
collect2: error: ld returned 1 exit status
CMakeFiles/train.dir/build.make:130: recipe for target 'train' failed
make[2]: *** [train] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/train.dir/all' failed
make[1]: *** [CMakeFiles/train.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Can anyone give me some advice about this?Thx~

**Comment by davheld** [comment]
@fujihuang How did you fix this?

**Comment by ghost** [comment]
Hi,thank you for your sharing.And i am sorry that when i closed this issue,i did not offer the way to solve this issue~
And this is the caffe camke problem, i asked there ,and someone told me just do as below is ok,and it really worked:
(before you do as below,you have to make sure you have the cmake gui installed)
1 Once you are in the build directory
ccmake ..
This will open like a gui in the terminal
2 if you press "t" you get all the possible options
3 then I have disable CUDA_USE_STATIC_CUDA_RUNTIME (if you are on teh flag just press enter to enable On or disbale OFF)
4. press c to configure
5 press g to generate
6 make all

(ps:it just use the gui and worked,i have tried to use the command to turn off the CUDA_STATIC_CUDA_RUNTIME, but it did not work,maybe it must use the gui~?)
