### ISSUE TITLE
Issue with evaluating the ALOV300++ dataset

### ISSUE THREAD

**Issue by pallavivm91** [davheld/GOTURN#30]
When I am trying to evaluate my tracker using the ALOV300++ dataset in http://imagelab.ing.unimore.it/dsm/index.php I couldnt proceed further because in the Trackers tab, I am unable to choose any category as after selecting the ALOV300++ no category is been loaded.

Is there any work around or any other site for doing the same?

**Comment by davheld** [comment]
I only used ALOV300++ for training and validation (not for testing), so I didn't need to compare my tracker to other trackers on this dataset.
