### ISSUE TITLE
Could GOTURN be run with CPU only?

### ISSUE THREAD

**Issue by akita1987** [davheld/GOTURN#39]
### I find simply uncomment some lines related to Caff and CUDA in CMakeLists.txt,then I met some fatal error like "/home/wxb/git/caffe/GOTURN/src/network/regressor.h:4:27: fatal error: caffe/caffe.hpp: No such file or directory". I guess GOTURN can not be run without GPU and CUDA installed.

But I found some information in your paper:
"On an Nvidia GeForce GTX Titan X GPU with cuDNN acceleration, our tracker runs at 6.05 ms per frame (not including the 1 ms to load each image in OpenCV), or 165 fps. On a GTX 680 GPU, our tracker runs at an average of 9.98 ms per frame, or 100 fps. **If only a CPU is available, the tracker runs at 2.7 fps.**"

Look at the bold text, does that mean GOTURN can be run with CPU only?If that's true, what should I do?

Thank you!

**Comment by davheld** [comment]
It's been a while, but I believe you can just add
#define CPU_ONLY 1
at the top of your main cpp file.

**Comment by akita1987** [comment]
@davheld Thank you for your help, but I don't really know which cpp file I should add this statement to? I add it to src/train/train.cpp, then I get an error below:
![screenshot from 2017-03-02 12-38-36](https://cloud.githubusercontent.com/assets/17294093/23493295/a25590c2-ff45-11e6-81bb-5b27ef5dfb77.png)
It is failed when I try to cmake . I don't know what's wrong. Could you please tell me which cpp file I should add it to?
Many thanks!

**Comment by davheld** [comment]
If you are not using the GPU, then you should remove the lines about CUDA from the CMakeLists.txt.

**Comment by akita1987** [comment]
Follow your instruction, I configure my CMakeLists.txt like this:

![cmakelists](https://cloud.githubusercontent.com/assets/17294093/23500793/350faba2-ff6c-11e6-8f89-746ee8328d42.png)

and I also configure GOTURN/cmake/Modules/FindCaffe.cmake like this:

![findcaffe](https://cloud.githubusercontent.com/assets/17294093/23500854/6cf07074-ff6c-11e6-801a-4aefe5e26bb5.png)

After all are done, I excute cmake in /build directory, and it successes with only a few warnings like this:

"WARNING: Target "test_tracker_alov" requests linking to directory "/home/wxb/git/caffe/build/lib".  Targets may link only to libraries.  CMake is dropping the item."

But after I excute "make" order, a fatal error happend:

![fatal_error](https://cloud.githubusercontent.com/assets/17294093/23500952/f0f90868-ff6c-11e6-97ea-21e3df7c9e55.png)

Can't find "cublas_v2.h". That's weird. I open the file "device_alternate.hpp", locate to line 34 and find that "cublas_v2.h" will be included only if CPU_ONLY=0. But I certainly define CPU_ONLY=1 in Makefile.configure before installing caffe. 

I google a lot and find some people have the same problem(https://github.com/BVLC/caffe/issues/2704). I still don't know how to solve the error. Do you have any idea about this error? I hope not wasting you too much time.Thank you very much.

**Comment by davheld** [comment]
Did you build CAFFE with -DCPU_ONLY?

**Comment by akita1987** [comment]
NO, shoud I build Caffe like order below?

cmake -D CPU_ONLY=ON ..

**Comment by davheld** [comment]
Not sure, but I think it could be worth a shot.  Sorry I can't help more at
this point.

**Comment by akita1987** [comment]
I add -DCPU_ONLY when build Caffe and all are normal. But when building GOTURN, the error is still there, even when I try to build GOTURN with -DCPU_ONLY. 

This error almost made me crazy now. I want to give up and be back to my lab's server. Anyway, I appreciate your help, you help me a lot. Now I'm reading the source, if I have any questions, could I email you?

Thanks a lot! Have a good weekend!

**Comment by akita1987** [comment]
@davheld Hi, finally I solved all errors and now I can run GOTURN with CPU only on my ubuntu 16.04LTD. Here are my advices:
   （1）To run with CPU only, uncomment CPU_ONLY=1 and TEST_GPUID := 0, and comment all items related to CUDA. Then compile Caffe with "cmake -DCPU_ONLY=ON .." in /build directory, if not , you may find CPU_ONLY equal OFF in the return information of cmake . Also you should add "#define CPU_ONLY 1" to all header files in /src/network directory. Beside , I also follow @davheld's advice and add it to other main cpp files in other directory like /train.
   （2）After Caffe is successfully installed and tested, firstly install trax (#2) (just download and make it), or you will meet errors like "undefined reference to `trax_server_setup" during make. Then configure GOTURN/CMakeLists.txt like below:

![screenshot from 2017-03-03 11-52-17](https://cloud.githubusercontent.com/assets/17294093/23537563/e0086ba2-0007-11e7-9043-625352386bab.png)
![screenshot from 2017-03-03 11-53-15](https://cloud.githubusercontent.com/assets/17294093/23537589/063802c4-0008-11e7-8aeb-9e6c950751ba.png)
(Caff_LIBRARIES should be set to /path-to-caffe/build/install/lib/libcaffe.so, not /path-to-caffe/build/install/lib. If not , errors like "Target:...requests linking to directory ...Targets may link only to libraries.  CMake is dropping")

and congiure GOTURN/cmake/Modules/FindCaffe.cmake like this:

![screenshot from 2017-03-03 11-55-58](https://cloud.githubusercontent.com/assets/17294093/23537637/61e52318-0008-11e7-93f8-6e7ff4531f5a.png)

   （3）Finally, build GOTURN using "cmake -DCPU_ONLY=ON .." and then make it.
Maybe some statments are reduntant, but I meet a hell lot of errors before I configure these two files right. @davheld gives me a lot help, thank you again!

**Comment by allensu0314** [comment]
@akita1987 Hi, I wanna test this amazing alg in CPU mode too.
Could you tell me how to run the program to test VOT2014? or did you change the scripts in bash folder?
Thank you !

**Comment by SoulmateB** [comment]
@akita1987 I have followed your advices, and add "#define CPU_ONLY 1" to the header files in /src/network ,and add it to the other main cpp, but I  also have the same problem "cublas_v2.h:no such file...". Could you please tell me the details? which cpp file I should add it to?  Thank you !!

**Comment by akita1987** [comment]
@SoulmateB Hi, you may try to add " -DCPU_ONLY=ON" when cmake GOTURN in /build directory.

**Comment by akita1987** [comment]
@ChaselS314 Sorry I 'm working on your problem too. But I believe you can find a way link in README file.

**Comment by akita1987** [comment]
@ChaselS314 Sorry I 'm working on your problem too. But I believe you can find a way link in README file.

**Comment by bei91** [comment]
@SoulmateB   I also have the same problem. Could you please tell me your solution? Thank you!

**Comment by davheld** [comment]
I just merged #43 by @brunobowden which should solve this issue.  Let me know if there is still a problem.

**Comment by shouguicai** [comment]
I am trying to train the caffe model on cpu only server(which has 64 cups), only one cup is used.
Can i set the it to use as much cpu as i have to train,just  like tensorflow do?

**Comment by foolwood** [comment]
@shouguicai 
you can try our matconvnet version.(not official)
https://github.com/foolwood/GOTURN_matconvnet

It's rather fast in CPU.

**Comment by pengfeix** [comment]
[ 57%] Building CXX object CMakeFiles/test_tracker_alov.dir/src/test/test_tracker_alov.cpp.o
make[2]: *** No rule to make target '/home/xpf/task1/caffe/build/lib/libcaffeproto.a', needed by 'test_tracker_alov'。 停止。
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/test_tracker_alov.dir/all' failed
make[1]: *** [CMakeFiles/test_tracker_alov.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
When I compiled the goturn,I met this error,could you give me any help?

**Comment by pengxin99** [comment]
@pengfeix 
try to git trax form https://github.com/votchallenge/trax.git,and then compile it by cmake, make like what guturn did .
