### ISSUE TITLE
error run tracker_test_vot : region.txt not available  

### ISSUE THREAD

**Issue by Jumabek** [davheld/GOTURN#5]
Hello,
I was trying to test the tracker so I run below command :

`./build/test_tracker_vot nets/models/pretrained_model/tracker.prototxt nets/models/pretrained_model/caffenet_train_iter_500000.caffemodel  1
`

And received following error:

```
Setting up Caffe in GPU mode with ID: 1
Setting phase to test
Network image size: 227, 227
Initial region file (region.txt) not available. Stopping.
```

I tried to follow VOT integration tutorial.
However, it seems you already included toolkit files in src/native dir.

Could you help me out or point some direction?
Do I need to take some action to integrate tracker with test_tracker_vot.cpp ?

Thanks!

**Comment by davheld** [comment]
The file test/test_tracker_vot.cpp is designed to integrate into the VOT testing framework - http://www.votchallenge.net/howto/index.html - follow these instructions:
http://www.votchallenge.net/howto/workspace.html
http://www.votchallenge.net/howto/integration.html (first section: Integrating tracker into the VOT toolkit)
http://www.votchallenge.net/howto/perfeval.html
http://www.votchallenge.net/howto/analysis.html

To just run the tracker on the VOT videos, use save_videos_vot.cpp
