### ISSUE TITLE
undefined reference error

### ISSUE THREAD

**Issue by hanlhan** [davheld/GOTURN#57]
Hi everyone,
When I run make the GOTURN, undefined reference occurred:
`[ 54%] Built target GOTURN
Scanning dependencies of target test_tracker_alov
[ 57%] Building CXX object CMakeFiles/test_tracker_alov.dir/src/test/test_tracker_alov.cpp.o
[ 60%] Linking CXX executable test_tracker_alov
libGOTURN.a(helper.cpp.o)：in function ‘__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > boost::re_detail_106200::re_is_set_member<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, char, boost::regex_traits<char, boost::cpp_regex_traits<char> >, unsigned int>(__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::re_detail_106200::re_set_long<unsigned int> const*, boost::re_detail_106200::regex_data<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, bool)’：
helper.cpp:(.text._ZN5boost16re_detail_10620016re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SH_SH_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb[_ZN5boost16re_detail_10620016re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SH_SH_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb]+0x172)：‘boost::re_detail_106200::cpp_regex_traits_implementation<char>::transform_primary(char const*, char const*) const’ undefined reference
helper.cpp:(.text._ZN5boost16re_detail_10620016re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SH_SH_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb[_ZN5boost16re_detail_10620016re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SH_SH_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb]+0x362)：‘boost::re_detail_106200::cpp_regex_traits_implementation<char>::transform(char const*, char const*) const’undefined reference
collect2: error: ld returned 1 exit status
CMakeFiles/test_tracker_alov.dir/build.make:125: recipe for target 'test_tracker_alov' failed
make[2]: *** [test_tracker_alov] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/test_tracker_alov.dir/all' failed
make[1]: *** [CMakeFiles/test_tracker_alov.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2`

My cmake result is:
`-- The C compiler identification is GNU 5.4.1
-- The CXX compiler identification is GNU 5.4.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No build type selected, default to Release
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   regex
-- Found TinyXML: /usr/lib/x86_64-linux-gnu/libtinyxml.so  
Open CV version is 2.4.9.1
Opencv_DEFINITIONS is 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr (found version "9.0") 
CUDA_INCLUDE_DIRS is /usr/include
Caffe_LIBRARIES HINTS is /home/harry/program/caffe/build/lib
Caffe_LIBRARIES is /home/harry/program/caffe/build/lib/libcaffe.so
Caffe_DEFINITIONS is -DCPU_ONLY
Caffe_DIR is /home/harry/program/caffe
Caffe_INCLUDE_DIRS is /home/harry/program/caffe/include
-- Configuring done
-- Generating done`
Could anyone help me?

**Comment by zhenxili96** [comment]
For the undefined boost::re_detail error, I got the same trouble like yours. What I did was changing the version of boost(from 1..60 to 1.65), and it worked.

**Comment by hanlhan** [comment]
thank you very much. @zhenxili96
