### ISSUE TITLE
Understanding the ground truth

### ISSUE THREAD

**Issue by RJVisee44** [davheld/GOTURN#78]
Hi everyone, 

I am relatively new to the world of object tracking. I don't understand why the ground truth labels for VOT and ALOV contain 8 coordinates (I believe it's the same bounding box but rotated?) In VOT it's the 2nd and 4th coordinate rotated and in ALOV it's the 1st and 3rd... why? 

Also, how are these coordinates interpreted? How can they be translated to (xmin, ymin, xmax, ymax)? Any help understanding would be much appreciated!

**Comment by johnSmith1990** [comment]
Do you find out? the use of annotations?
